
## 3. Array Indexing and Slicing

### Basic Indexing and Slicing Techniques
In NumPy, multidimensional arrays can be indexed using a tuple of integers or slices. This concept is crucial when working with data in multiple dimensions.

- **Single Element Access:** To access a single element in a multidimensional array, you specify a tuple of indices corresponding to each dimension. For example, `array[i, j]` accesses the element at row `i` and column `j` in a 2D array.

- **Row and Column Access:** To access an entire row or column, use a slice (`:`) for the dimension you want to include entirely. For example, `array[i, :]` gets the entire `i`th row, and `array[:, j]` gets the `j`th column.

Let's see some examples:



In [ ]:
# List indexing
lis = [[1, 2, 3, 4],[1,2,3]]
lis[0][1]

2

In [ ]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

Element at row 1, column 2: 6


In [ ]:
# List slicing
li = [1, 2, 3, 4, 5, 6]
li[1:3]

[2, 3]



#### Comprehensive Teaching of Slicing

Slicing in NumPy is a method to extract a portion of an array. It's similar to slicing in Python lists, but it extends to multiple dimensions.

- **Syntax:** Slicing uses the colon (`:`) syntax, like `array[start:stop:step]`. If `start` or `stop` are omitted, they default to the beginning and end of the array, respectively. If `step` is omitted, it defaults to 1.

- **Slicing in Multiple Dimensions:** In a 2D array, `array[i:j, k:l]` slices rows `i` to `j-1` and columns `k` to `l-1`.

Here are some slicing examples:



In [ ]:
# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [ ]:
# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])



![indexing and slicing](https://drive.google.com/uc?id=1A5p76BgaczkPR7EN3uCpPpffQxNbQ-ld)

### Advanced Indexing: Boolean and Fancy Indexing

NumPy also supports advanced indexing techniques like boolean indexing and fancy indexing, which are powerful tools for data analysis.





#### Note on Advanced Indexing and Shapes

Advanced indexing techniques in NumPy, like boolean indexing, can return arrays of different shapes compared to the original array. For instance, boolean indexing often results in a 1D array, regardless of the original array's dimensions.

Example of Boolean Indexing:



In [ ]:
# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array)
# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array

[[1 2]
 [3 4]
 [5 6]]
Result of Boolean Indexing: [4 5 6]


In [ ]:
# Boolean indexing
print("Elements greater than 25:", array[array > 25])

# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 2]])

Elements greater than 25: []
Select specific elements: [[3 4]
 [5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[[2,5]])

[3 6]


In [ ]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array[[1,2],[0,1]]

array([3, 6])



**Expected Output**:
- Specific elements based on the given conditions in both boolean and fancy indexing.

### Important Concepts

- **Boolean Indexing**: This allows you to select elements from an array that meet certain conditions. It's like filtering based on array values.
- **Fancy Indexing**: This involves passing an array of indices to access multiple array elements at once. It's useful for accessing non-adjacent elements.

# Table for Indexing Types and Examples

| Indexing Type | 1D Example | 2D Example | 3D Example |
|---------------|------------|------------|------------|
| Single Index | `array_1d[2]` | `array_2d[1, 0]` | `array_3d[0, 1, 1]` |
| Slice | `array_1d[1:3]` | `array_2d[0:2, 1:3]` | `array_3d[0, 1:3, 1:3]` |
| Boolean Indexing | `array_1d[array_1d > 2]` | `array_2d[array_2d % 2 == 0]` | `array_3d[array_3d < 5]` |
| Fancy Indexing | `array_1d[[0, 3]]` | `array_2d[:, [1, 2]]` | `array_3d[[0, 1], [1], [1]]` |


## Exercise: Practicing Indexing and Slicing

1. **Basic Indexing**: Create an array of 10 elements and access the 5th element in it.
2. **Basic Slicing**: From the same array, extract a slice containing the 3rd to the 8th elements.
3. **Boolean Indexing**: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.
4. **Fancy Indexing**: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.

**Expected Output**:
- The 5th element of the first array.
- A slice of the array showing elements from the 3rd to the 8th position.
- Elements greater than 30 from the random array.
- Selected elements (2nd, 4th, 6th) from the random array using fancy indexing.

---




In [ ]:
first = [1,3,4,2,3,4,3,2,3,4]
print(first[4])
print(first[2:8])

third = np.random.randint(10, 50, 6)
print(third)
third[[1,3,5]]

3
[4, 2, 3, 4, 3, 2]
[18 16 22 25 11 22]


array([16, 25, 22])

## Random Number Generation in Numpy
We can easily create an array of random integers in a specific using Numpy with the function from the Numpy random module called randint:

In [ ]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])

[44 49 37]


### Random Permutations
You can mix up an array using the numpy function random.permutation:

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([3, 7, 1, 4, 6, 2, 5])

In [ ]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[5, 6],
       [1, 2],
       [3, 4]])

### Create a list of integers
You can easily create a list of integers in a specific range in Numpy using the arrange function:

In [ ]:
x = np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Changing the NumPy Array with Indexing and Slicing

Modifying arrays using indexing and slicing is a key aspect of data manipulation in NumPy. This approach offers efficient and flexible ways to change array data.

#### Basic Indexing for Modification
Access individual elements or a series of elements in an array using their indices to modify them.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]

[ 1  2 10  4  5]




#### Slicing for Bulk Modifications
Select and modify a subset of an array. Useful for bulk operations.



In [ ]:
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [1, 20, 30, 40, 5]

[ 1 20 30 40  5]




#### Boolean Indexing for Conditional Modification
Use boolean indexing for conditional selection and modification of elements.



In [ ]:
print(arr)
arr[arr > 10] = 100
print(arr)  # Output: [1, 100, 100, 100, 5]

[ 1 20 30 40  5]
[  1 100 100 100   5]




#### Advanced Indexing Techniques
Modify elements in non-adjacent positions or follow a specific pattern.



In [ ]:
arr[np.array([1, 3])] = 500
print(arr)  # Output: [1, 500, 100, 500, 5]



#### Impact of Slicing on Original Array
Slicing creates a view, not a copy. Modifications through a slice affect the original array.



In [ ]:
sub_arr = arr[1:3]
sub_arr[0] = 600
print(arr)  # Output: [1, 600, 100, 500, 5]

In [ ]:
# # Making a copy of an array
a = np.array([1,2,3,4])
# b = a.copy()
b = np.array(a)
b[0] = 10
print(a, b)

[1 2 3 4] [10  2  3  4]




### Exercises on Indexing and Slicing for Array Modification

After learning about array indexing and slicing, it's important to practice these concepts. Here are some exercises to help solidify your understanding:

1. **Modifying Specific Elements**:
   Create an array with values from 1 to 10. Change the value of the fifth element to 50.

2. **Slicing and Modifying a Range**:
   Given an array of 10 elements, modify the elements from index 3 to 7 to be their negative equivalent.

3. **Conditional Modification with Boolean Indexing**:
   Create an array with 20 random integers between 1 and 100. Set all values greater than 50 to -1.

4. **Advanced Indexing Modification**:
   Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.

5. **Understanding Slicing Impact**:
   Create an array of 10 elements. Slice the array from index 2 to 5, and modify the first element of the slice. Observe the change in the original array.


In [ ]:
x = np.arange(1,11)
x[4] = 50
x[3:8] = x[3:8] * -1

In [ ]:
y = np.random.randint(1,100,20)
print(y)
y[y>50] = -1
y

[37 26 39 40 84 58 33 51 38 67 30 94  7 41 65 30 30 66  4 44]


array([37, 26, 39, 40, -1, -1, 33, -1, 38, -1, 30, -1,  7, 41, -1, 30, 30,
       -1,  4, 44])

In [ ]:
two = np.arange(25).reshape((5,5))
two

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
two[[np.arange(5)],[np.arange(5)]] = two[[np.arange(5)],[np.arange(5)]] * 2

In [ ]:
two

array([[ 0,  1,  2,  3,  4],
       [ 5, 12,  7,  8,  9],
       [10, 11, 24, 13, 14],
       [15, 16, 17, 36, 19],
       [20, 21, 22, 23, 48]])

In [ ]:
origin = np.arange(10)
origin

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slic = origin[2:5]
slic[0] = 99
print(origin)
print(slic)

[ 0  1 99  3  4  5  6  7  8  9]
[99  3  4]
