In [1]:
import numpy as np


In [5]:
#Exercice 1
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Array:", array_1d)


1D Array: [0 1 2 3 4 5 6 7 8 9]


In [7]:
#Exercice 2
my_list = [3.14, 2.17, 0, 1, 2]

array = np.array(my_list)

array = array.astype(int)

print(array)


[3 2 0 1 2]


In [10]:
#Exercice3
array_3 = np.arange(1, 10).reshape(3, 3)

print(array_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Exercise4

random_values = np.random.rand(4, 5)
array_2d = random_values.reshape(4, 5)

print(array_2d)

[[0.83236587 0.75056456 0.68821323 0.61221078 0.3105686 ]
 [0.85228142 0.16304033 0.65775999 0.02857633 0.90380581]
 [0.88170287 0.17627295 0.1641314  0.9919353  0.64502712]
 [0.06026292 0.71261568 0.48258344 0.94048423 0.3104877 ]]


In [14]:
#Exercise 5
given_array = np.array([
    [0, 1, 2, 3, 4],
    [20, 21, 22, 23, 24],
    [40, 41, 42, 43, 44]
])
second_row = given_array[1]

print(second_row)


[20 21 22 23 24]


In [19]:
#Exercice6
array_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reversed_array = array_1[::-1]
print(reversed_array)


[9 8 7 6 5 4 3 2 1 0]


In [23]:
#Exercise7
matrix = np.identity(4)

print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#Exercise8
array_x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Sum:", np.sum(array_x))
print("Average:", np.mean(array_x))



Sum: 45
Average: 5.0


In [33]:
#Exercise 9
array = np.arange(1, 21).reshape(4, 5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#Exercise 10


In [36]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = array[array % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
